### PR TITLE
Ruby convention is to use the default rake task to run tests

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by azaroth42** [comment]
+1.  Can we capture these in the best practices for future reference?

**Comment by dazza-codes** [comment]
In this case, there is a lot of work to be done on filling in the tests.  This project has been developed "in a hurry" with various refactoring along the way, to discover code patterns that will work for navigating IIIF data.  It's now looking a little more settled and work has begun to extract more general utils from it (e.g., triannon-client and rdf-resource), including more rigorous tests across the board.

For details on the source of the code convention adopted, see
http://blog.howareyou.com/post/66375371138/ruby-apps-best-practices

The patterns described there have been working well for me.  I'm open to alternatives where I can see advantages to the alternative and also understand the shortcomings of an approach using ENV.

Lastly, you may have to look at triannon-client to see a more complex ./bin/test.sh that does some management of .env files to ensure that tests run with the default .env_example settings.  This allows development work with modified .env settings, while ensuring that tests always run with .env_example settings.  See
https://github.com/sul-dlss/triannon-client/blob/master/bin/test.sh

This discussion may be a larger topic that this specific pull request.  We may have to take it offline or elsewhere online.

**Comment by cbeer** [comment]
Thanks for the pointer to triannon-client. That looks a lot more fleshed out.

**Comment by azaroth42** [comment]
Can we surface the issue in DLSS more broadly to get feedback?

**Comment by dazza-codes** [comment]
@azaroth42 - see https://github.com/sul-dlss/DeveloperPlaybook/issues/5

**Comment by azaroth42** [comment]
Thanks! Will discuss with Bess. (assigning to me until we can proceed)

**Comment by dazza-codes** [comment]
This is a destructive PR that fails to replace the desired behavior for testing.  Submit a more constructive solution that can replace ./bin/test.sh and manage the test settings provided in .env_example

**Pull request closed without merging**
